username: 'user@gmail.com'
size:
  width: 26
  height: 10
views:
  default:
    type: grid
    query:
  yellow:
    query:
      type: grid
      name: Yellow
      colors:
      - yellow
      pinned: true
      labels:
      - todo
      archived: false
